=== Isradrg/ASIR-Lenguaje-de-Marcas.-Ejercicios-realizados/Tarea.5.4.PrimerXSD-XML-Modulos/Tarea.5.4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="asir">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="horario" type="HorarioType" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:complexType name="HorarioType">
        <xsd:sequence>
            <xsd:element name="curso" type="xsd:integer" />
            <xsd:element name="modulo" type="xsd:string" />
            <xsd:element name="horas" type="HorasType" maxOccurs="unbounded" />
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="HorasType">
        <xsd:sequence>
            <xsd:element name="horascurriculo" type="xsd:integer" />
            <xsd:element name="horassemanales" type="xsd:integer" />
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== Isradrg/ASIR-Lenguaje-de-Marcas.-Ejercicios-realizados/Tarea.5.4.PrimerXSD-XML-Modulos/Tarea.5.4.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Diccionario: asir, horario, curso, modulo, horas curriculo, horas semanales
Reglas: asir tiene un horario, en el horario, sale el año del curso, el nombre del módulo,
las horas semanales, tanto del curriculo como las semanales-->
<asir xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="./Tarea.5.4.xsd">
    <horario>
        <curso>1</curso>
        <modulo>ISO</modulo>
        <horas>
            <horascurriculo>230</horascurriculo>
            <horassemanales>7</horassemanales>
        </horas>

        <curso>1</curso>
        <modulo>PAR</modulo>
        <horas>
            <horascurriculo>160</horascurriculo>
            <horassemanales>6</horassemanales>
        </horas>

        <curso>1</curso>
        <modulo>FHD</modulo>
        <horas>
            <horascurriculo>100</horascurriculo>
            <horassemanales>4</horassemanales>
        </horas>

        <curso>1</curso>
        <modulo>GBD</modulo>
        <horas>
            <horascurriculo>160</horascurriculo>
            <horassemanales>5</horassemanales>
        </horas>

        <curso>1</curso>
        <modulo>LMSGI</modulo>
        <horas>
            <horascurriculo>130</horascurriculo>
            <horassemanales>4</horassemanales>
        </horas>

        <curso>2</curso>
        <modulo>ASO</modulo>
        <horas>
            <horascurriculo>145</horascurriculo>
            <horassemanales>7</horassemanales>
        </horas>

        <curso>2</curso>
        <modulo>SRI</modulo>
        <horas>
            <horascurriculo>145</horascurriculo>
            <horassemanales>8</horassemanales>
        </horas>

        <curso>2</curso>
        <modulo>IAW</modulo>
        <horas>
            <horascurriculo>100</horascurriculo>
            <horassemanales>5</horassemanales>
        </horas>

        <curso>2</curso>
        <modulo>ASGBD</modulo>
        <horas>
            <horascurriculo>60</horascurriculo>
            <horassemanales>3</horassemanales>
        </horas>

        <curso>2</curso>
        <modulo>SAD</modulo>
        <horas>
            <horascurriculo>100</horascurriculo>
            <horassemanales>6</horassemanales>
        </horas>
    </horario>
</asir>
