=== Isradrg/ASIR-Lenguaje-de-Marcas.-Ejercicios-realizados/Tarea.5.2.CentroMedico/centromedico.dtd
<!ELEMENT centromedico (nombre,fecha,listascitas)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>
<!ELEMENT listascitas (citas)>
<!ELEMENT citas (cita+)>
<!ELEMENT cita (codigo,companyaprivada,horaasignada,horallamada,tiempoespera,estado)>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT companyaprivada EMPTY>
<!ELEMENT horaasignada (#PCDATA)>
<!ELEMENT horallamada (#PCDATA)>
<!ELEMENT tiempoespera (#PCDATA)>
<!ELEMENT estado (#PCDATA)>

=== Isradrg/ASIR-Lenguaje-de-Marcas.-Ejercicios-realizados/Tarea.5.2.CentroMedico/centromedico.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE centromedico SYSTEM "centromedico.dtd">
<centromedico>
    <nombre>Centro MÃ©dico Salux Infurmorum</nombre>
    <fecha>23-03-2021</fecha>
    <listascitas>
        <citas>
            <cita>
                <codigo>05EDC</codigo>
                <companyaprivada></companyaprivada>
                <horaasignada>9:05</horaasignada>
                <horallamada>9:07</horallamada>
                <tiempoespera>2m</tiempoespera>
                <estado>O</estado>
            </cita>

            <cita>
                <codigo>07WEV</codigo>
                <companyaprivada></companyaprivada>
                <horaasignada>10:00</horaasignada>
                <horallamada>10:30</horallamada>
                <tiempoespera>30m</tiempoespera>
                <estado>D</estado>
            </cita>
        </citas>
    </listascitas>
</centromedico>
