=== Isradrg/ASIR-Lenguaje-de-Marcas.-Ejercicios-realizados/Tarea.5.5.XSD-XML-ProductosConAtributos/lista.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="listaproductos">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="producto" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="descripcion" minOccurs="0" type="xs:string" />
              <xs:element name="peso" type="xs:decimal" />
            </xs:sequence>
            <xs:attribute name="codigo" use="required" />
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Isradrg/ASIR-Lenguaje-de-Marcas.-Ejercicios-realizados/Tarea.5.5.XSD-XML-ProductosConAtributos/lista.xml
<listaproductos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="./lista.xsd">
  <producto codigo="DX-22"><!--Codigo obligatorio-->
    <descripcion>Ordenador</descripcion><!--Optativa-->
    <peso>23.44</peso><!--Positivo con decimales-->
  </producto>
  <producto codigo="CX-124">
    <peso>17.50</peso>
  </producto>
  <producto codigo="CX-124">
    <peso>17.50</peso>
  </producto>
</listaproductos>
